In [8]:
import pandas as pd
from google.colab import drive
import os
import plotly.express as px
# drive.mount('/content/gdrive', force_remount=True)

tabela = pd.read_excel('Vendas.xlsx')
display(tabela)

ModuleNotFoundError: No module named 'google'

In [7]:
# faturamento por loja
faturamento_loja = tabela[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()
display(faturamento_loja)

NameError: name 'tabela' is not defined

In [ ]:
"""# faturamento por produto 
faturamento_loja = tabela[['ID Loja', 'Valor Final', 'Produto']].groupby(['ID Loja', 'Produto']).sum()
display(faturamento_loja)"""

                                             Valor Final
ID Loja                    Produto
Bourbon Shopping SP        Bermuda                   750
                           Bermuda Estampa          1183
                           Bermuda Linho             195
                           Bermuda Listrado         1793
                           Bermuda Xadrez            465
Center Shopping Uberl√¢ndia Bermuda Estampa           338
                           Bermuda Linho             780
                           Bermuda Listrado          326
                           Bermuda Xadrez           1550
Iguatemi Campinas          Bermuda                  1200
                           Bermuda Estampa           845
                           Bermuda Linho            1170
                           Bermuda Liso            36581
                           Bermuda Listrado         1304
                           Bermuda Xadrez            620
Iguatemi Esplanada         Bermuda                   150
                           Bermuda Estampa           338
                           Bermuda Linho            1365
                           Bermuda Xadrez            620
Norte Shopping             Bermuda                  1350
                           Bermuda Estampa           845
                           Bermuda Linho             390
                           Bermuda Listrado          652
                           Bermuda Xadrez           1085

Intensiv√£o aula 2

In [ ]:
# passo 1 = Importar a base de dados
tabela = pd.read_excel('gdrive/My Drive/analise_dados/Vendas.xlsx')

         Data                     ID Loja  ... Valor Unit√°rio  Valor Final
0  2019-12-01           Iguatemi Campinas  ...            169          169
1  2019-12-01          Iguatemi Esplanada  ...            155          155
2  2019-12-01              Norte Shopping  ...            150          300
3  2019-12-01           Iguatemi Campinas  ...            163          489
4  2019-12-01           Iguatemi Campinas  ...            195          585
5  2019-12-03           Iguatemi Campinas  ...            155          155
6  2019-12-03         Bourbon Shopping SP  ...            163          163
7  2019-12-03         Bourbon Shopping SP  ...            155          465
8  2019-12-03         Bourbon Shopping SP  ...            169          169
9  2019-12-04  Center Shopping Uberl√¢ndia  ...            155          620
10 2019-12-04          Iguatemi Esplanada  ...            150          150
11 2019-12-04         Bourbon Shopping SP  ...            169          338
12 2019-12-04           Iguatemi Campinas  ...            150          600
13 2019-12-05           Iguatemi Campinas  ...            157         8635
14 2019-12-05           Iguatemi Campinas  ...            150          600
15 2019-12-05         Bourbon Shopping SP  ...            163          163
16 2019-12-06          Iguatemi Esplanada  ...            169          169
17 2019-12-07           Iguatemi Campinas  ...            155          155
18 2019-12-07         Bourbon Shopping SP  ...            150          450
19 2019-12-08  Center Shopping Uberl√¢ndia  ...            195          780
20 2019-12-08           Iguatemi Campinas  ...            169          676
21 2019-12-09          Iguatemi Esplanada  ...            155          465
22 2019-12-10  Center Shopping Uberl√¢ndia  ...            163          163
23 2019-12-11           Iguatemi Campinas  ...            155          155
24 2019-12-11              Norte Shopping  ...            155          310
25 2019-12-12          Iguatemi Esplanada  ...            195          195
26 2019-12-14         Bourbon Shopping SP  ...            195          195
27 2019-12-15           Iguatemi Campinas  ...            195          585
28 2019-12-15  Center Shopping Uberl√¢ndia  ...            155          155
29 2019-12-15         Bourbon Shopping SP  ...            163          326
30 2019-12-16              Norte Shopping  ...            163          163
31 2019-12-16         Bourbon Shopping SP  ...            163          326
32 2019-12-17              Norte Shopping  ...            155          155
33 2019-12-17           Iguatemi Campinas  ...            163          652
34 2019-12-17         Bourbon Shopping SP  ...            150          300
35 2019-12-17         Bourbon Shopping SP  ...            163          489
36 2019-12-18              Norte Shopping  ...            163          489
37 2019-12-18          Iguatemi Esplanada  ...            169          169
38 2019-12-19           Iguatemi Campinas  ...            163          163
39 2019-12-19  Center Shopping Uberl√¢ndia  ...            169          169
40 2019-12-19  Center Shopping Uberl√¢ndia  ...            169          169
41 2019-12-19              Norte Shopping  ...            150          150
42 2019-12-20         Bourbon Shopping SP  ...            163          326
43 2019-12-20          Iguatemi Esplanada  ...            195          195
44 2019-12-21              Norte Shopping  ...            169          845
45 2019-12-21              Norte Shopping  ...            150          600
46 2019-12-21          Iguatemi Esplanada  ...            195          975
47 2019-12-22           Iguatemi Campinas  ...            155          155
48 2019-12-22  Center Shopping Uberl√¢ndia  ...            163          163
49 2019-12-23              Norte Shopping  ...            195          390
50 2019-12-23              Norte Shopping  ...            150          300
51 2019-12-24  Center Shopping Uberl√¢ndia  ...            155          155
52 2019-12-24              Norte Shopping  ...            155          620
53 2019-12-24  Center Shopping Uberl√¢ndia  ...            155          620
54 2019-12-24           Iguatemi Campinas  ...            157        12246
55 2019-12-25           Iguatemi Campinas  ...            157        15700
56 2019-12-26         Bourbon Shopping SP  ...            169          676

[57 rows x 6 columns]

In [2]:
# Passo 2: Visualizar a base de dados
# Entender quais informa√ß√µes dispon√≠veis 
# Descobrir as cagadas na base de dados
tabela = tabela.drop('Data', axis=1) # excluir linha 0 linha 1 coluna
display(tabela)

NameError: name 'tabela' is not defined

In [5]:
# Passo 3 - tratamento na base de dados
# - valores que est√£o vazios
# - valores que s√£o numeros mas o python acha que e texto
# - Informa√ß√µes inuteis
tabela['Valor Final'] = pd.to_numeric(tabela['Valor Final'], errors="coerce") # Trasnformar string em n√∫mero 
# colunas vazias
tabela = tabela.dropna(how="all", axis=1) # all quando voc√™ quer excluir colunas tolmente vazias
# any √© quando voc√™ quer excluir a coluna quando 1 dados esta vazio 

# Linhas vazias
tabela = tabela.dropna(how="any", axis=0) 
print(tabela.info()) # Informa√ß√µes sobre a tabela

NameError: name 'pd' is not defined

In [4]:
# Passo 4: An√°lise exploratoria -> An√°lise geral 

display(tabela['ID Loja'].value_counts())
display(tabela['ID Loja'].value_counts(normalize=True).map('{:.1%}'.format))

NameError: name 'tabela' is not defined

In [3]:
# Passo 5: Olhando as colunas na base de dados - identificar o motivo dos clientes cancelaram 

for coluna in tabela.columns:
    print(coluna)
    grafico = px.histogram(tabela, x=coluna, color='Quantidade')
    grafico.show()

NameError: name 'tabela' is not defined